### ISSUE TITLE
SIGTRAN Configuration

### ISSUE THREAD

**Issue by inesromdhani** [RestComm/smscgateway#149]
We have an architecture (application server/SGW)  which communicates with an HLR et an MSC
please see the picture attached: callflow_sigtran.png

My questions are:

1) Should i create two associations (one for the HLR and the other for the MSC)

2) How should i configure the rooting so we can have the result described in the attached diagram; sequenceDiag-Sigtran.png

in the interface of smsc-management -> server settings -> SS7 settings menu, (please see ss7_Config.png) we should configure:

SRI requests configuration
-Pre-configured HLR address for SRI requests Network Id : 
-Pre-configured HLR address for SRI requests :  

Sub System Number Configuration
-SMSC Gateway subsystem number :
-HLR subsystem number :
-MSC subsystem number:

**Comment by inesromdhani** [comment]
![callflow_sigtran](https://cloud.githubusercontent.com/assets/6337655/20003205/8ff47b4a-a285-11e6-8b63-048256c483a9.png)
![sequencediag_sigtran](https://cloud.githubusercontent.com/assets/6337655/20003210/934e9ec4-a285-11e6-89ce-2874d420f472.png)

**Comment by vetss** [comment]
Hello @inesromdhani 

you should firstly config SS7 stack itself.
Check this manual: http://documentation.telestax.com/core/ss7/SS7_Stack_User_Guide.html

It is not possible to configure your server via this portal because it is for reporting of issues / problems of products and discussing of them. You need to read some manuals or ask a public forum if anybody can help you https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/restcomm or become a customer with a product support.

**Comment by inesromdhani** [comment]
Thank you @vetss  for your answer.
