### ISSUE TITLE
Enhancement: Enable sending of arbitrary Tlv/Optional Parameters in SMPP Simulator

### ISSUE THREAD

**Issue by abdulazizali77** [RestComm/smscgateway#191]
There is a need to send SMS Optional Parameters with the SMPP Simulator.
Potentially create a new dialog box or tab to display list of Tlvs included with SMS sent.
Should also check if Tlvs are standard Tlvs

**Comment by abdulazizali77** [comment]
@vetss Would this be an acceptable enhancement, and how do you think it should be done UI-wise?

**Comment by vetss** [comment]
Hello @abdulazizali77 

we can add a new Tab "Tlv" in "SMPP message parameters" dialog box with
- Check box ("Sending Tlv") unchecked by default (if we turn it on the an extra Tlv will be sent)
- TextBoxes with tag value / Tlv value

Please go ahead with implementation.

**Comment by vetss** [comment]
Hello @abdulazizali77 

can we finish this undate this week so we can include it into a next SMSC GW release that we age going to release in about 7-10 days ?

**Comment by vetss** [comment]
Hello @abdulazizali77 

thanks for your update. I have committed you update and my little fix.

The fix is for two tasks (please check my second commit ):
1) you have not fully added a new lib into release binaries
2) I changed litte bit names of fields in a Windows GUI form and a way of bad values into a form.

Fixed by:
https://github.com/RestComm/smscgateway/commit/8d7e50bafddb69a9861988d69e56747fc3682c1b
https://github.com/RestComm/smscgateway/commit/158e2e49070ec0a35cb58771300ba44d8c393c9c

**Comment by abdulazizali77** [comment]
thanks @vetss
