### ISSUE TITLE
Ported numbers in RestComm SMSC

### ISSUE THREAD

**Issue by LxB1982** [RestComm/smscgateway#285]
Hi. We are using the open source version of RestComm SMSC and have it connecting and sending to multiple MNO's. However, numbers ported from one MNO to another don't deliver at all and get rejected. The MNO's have stated that we are not performing porting lookups before sending the messages through to them. We do this within our own software before the messages reach the RestComm gateway, but then after that they fail. Is there any way of configuring this in the RestComm SMSC so that it sends through he correct information to the operator? Possibly in the MPROC or SS7 rules? Do we need an separate HLR that RestComm can talk to before trying to deliver the messages?

**Comment by nhanth87** [comment]
Hi,
For a ported number, if your country is small country (like Singapore), you will have a list of all ported number  then you can use `routing by database`

If your country is big, you need to do lookup for the ported number. You need to write your own mproc rule that query from Operator database to know where's the HLR for ported number.

Currently SMSC is not automatic do this because ported number is based on every country rule
