### ISSUE TITLE
Intermediate Delivery Reports

### ISSUE THREAD

**Issue by faizann** [RestComm/smscgateway#62]
There is usually a need on SMPP clients to get extra information about status of an SMS for reporting purposes. This requires having intermediate delivery reports for every temporary failures. 
We need a way to send intermedia DLRs for such failures so that SMPP client side knows what is really going on with an SMS.

Suggestion is to loop through sms in SmsSet in case there are no failured sms and create intermediary DLR. The MessageUtil.java needs to accept an extra param tempFailure in createReceiptSms for identifying if a DLR is for temporary (ENROUTE/BUFFERED) or final in case of failure.

**Comment by deruelle** [comment]
Thanks @faizann. Do you want to contribute this one and provide a Pull Request for this ?

**Comment by faizann** [comment]
I will do so.

**Comment by vetss** [comment]
Some comments:
- this feature must be configurable and disabled for default
- implementaion of this demands a major processing in methods like onDeliveryError() and a very accurate implementing. Now delivery receipts are generated only for messages in "lstFailured" (so for a permananet failure only). There are also other actions that are applied for such messages. We will need to change this logic - like adding of extra list "lstTempFailured" and processing of it for receipts purposes. Also we have several places for receipt generating code...

**Comment by faizann** [comment]
Yeah indeed it is not that simple. I have only looked at onDeliveryError
part in SS7 side. I think MProc rules should be skipped for temp failures.
lstFailured will have to stay independent.

Give me a few days and I will send a pull request. I will be working on it.

**Comment by deruelle** [comment]
@faizann just wondered if you had anything blocking to complete this  that we could help you with ?

**Comment by faizann** [comment]
Hi
I have nothing blocking. Just very busy with work. I will try to submit a
pull request next week.

**Comment by deruelle** [comment]
Thanks @faizann looking forward to it !

**Comment by deruelle** [comment]
hi @faizann, just wondering if you were able to move forward on that ?

**Comment by faizann** [comment]
Hi. I had messed up a lot of code on my local machine so had to cleanup. 
Here is the pull request https://github.com/RestComm/smscgateway/pull/77

**Comment by vetss** [comment]
Hi @faizann,

I have committed your update, thanks for your work.

But I have some remarks for your work.
- your update looks like a rough patch. We need to some more elegant solution like preparing a special list lstIntermediateReceipts like we have lstFailured and fill it during message processing. I understand that this is more complicated task but it looks more proper because we need to have a readable code. For general code refactoring I have created a special issue https://github.com/RestComm/smscgateway/issues/80
- I fixed one I guees bug - when in MT part we are sending IntermediateReceipts even when on originator does not ask it.
- usage of "lstFailured.indexOf(sms)" can lead some delays if we have many messages for delivering. This is an often case when sending to SMPP. So it is better to refactor this (if we refactor remark 1)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/6b67993b6b36cfd74158e4d58792418b07e770b7
https://github.com/RestComm/smscgateway/commit/998c419c5c79549ded352f5237e1d808ba3286be

It is better to refactor code to have more clear code.

**Comment by deruelle** [comment]
@faizann  acknowledged at https://telestax.com/acknowledgements/
